# copy from https://github.com/kakuemon/capture-tuna-bot-with-parrot/blob/master/app.yaml.sample

runtime: python37

env_variables:
  USER_ID: ""
  YOUR_CHANNEL_SECRET: ""
  YOUR_CHANNEL_ACCESS_TOKEN: ""

handlers:
# All URLs ending in .gif .png or .jpg are treated as paths to
# static files in the static/ directory. The URL pattern is a
# regular expression, with a grouping that is inserted into the
# path to the file.
- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
  # ...
